In [1]:
import pandas as pd

In [2]:
messages=pd.read_csv('spam new1.csv')
messages.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
messages=messages.drop('Unnamed: 2',axis=1)

In [4]:
messages=messages.drop('Unnamed: 3',axis=1)

In [5]:
messages=messages.drop('Unnamed: 4',axis=1)

In [6]:
messages.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
messages=messages.rename(columns={'v1':'label','v2':'message'})
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
import re

In [9]:
import nltk

In [10]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sameer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\sameer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [11]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [12]:
ps=PorterStemmer()
lemmatizer=WordNetLemmatizer()

In [13]:
corpus=[]

In [14]:
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]','',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [15]:
messages.head(3)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...

In [16]:
from sklearn.feature_extraction.text import CountVectorizer 

In [17]:
cv=CountVectorizer(max_features=1000)

In [18]:
X=cv.fit_transform(corpus).toarray()

In [40]:
pickle.dump(cv, open('transform.pkl','wb'))

In [19]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
messages.shape

(5572, 2)

In [21]:
y=pd.get_dummies(messages['label'])
y=y.iloc[:,1].values

In [22]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [24]:
from sklearn.naive_bayes import MultinomialNB

In [25]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [26]:
y_pred=spam_detect_model.predict(X_test)

In [27]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [28]:
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
confusion_m=confusion_matrix(y_test,y_pred)

In [31]:
confusion_m

array([[949,   0],
       [161,   5]], dtype=int64)

In [32]:
    from sklearn.metrics import accuracy_score

In [33]:
print(accuracy_score(y_test,y_pred))

0.8556053811659193


In [34]:
filename='nlp_model.pkl'

In [35]:
import pickle

In [37]:
pickle.dump(spam_detect_model,open(filename,'wb'))

In [41]:
import joblib

In [1]:
import tensorflow as tf

In [3]:
tf.__version__

'2.3.1'